{
 "title": "Technitium DNS",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "server",
    "query": {
     "query": "label_values(technitium_dns_server_urls,server)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Base URL",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "technitium_dns_server_urls{server=\"$server\"}",
     "legendFormat": "{{base_url}}"
    }
   ]
  },
  {
   "title": "Connection status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "technitium_dns_status{server=\"$server\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Update status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "technitium_dns_update_available{server=\"$server\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Zones managed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "technitium_dns_zone_count{server=\"$server\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of clients",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "technitium_dns_client_count{server=\"$server\"}",
     "legendFormat": "nb_clients"
    }
   ]
  },
  {
   "title": "Total requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(technitium_dns_request_result_count{server=\"elpain\"})",
     "legendFormat": "total"
    }
   ]
  },
  { "title": "Blocking", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Zones in block lists",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "technitium_dns_block_list_zone_count{server=\"$server\"}",
     "legendFormat": "value"
    }
   ]
  },
  {
   "title": "Blocked zones",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "technitium_dns_blocked_zone_count{server=\"$server\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Zones in allow lists",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "technitium_dns_allow_list_zone_count{server=\"$server\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Allowed zones",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "technitium_dns_allowed_zone_count{server=\"$server\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Results", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Requests results",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "technitium_dns_request_result_count{server=\"$server\"}",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Results over the last hour",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum_over_time(technitium_dns_request_result_count[1h])",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Record types over the last hour",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "technitium_dns_record_type_count{server=\"$server\"}",
     "legendFormat": "{{record_type}}"
    }
   ]
  },
  { "title": "Resolving", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Requests resolve modes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "technitium_dns_resolve_mode_count{server=\"$server\"}",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Resolving over the last hour",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum_over_time(technitium_dns_resolve_mode_count{server=\"$server\"}[1h])",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Protocols used over the last hour",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "technitium_dns_query_protocol_count{server=\"$server\"}",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  { "title": "Caching", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Cached entries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "technitium_dns_cached_entry_count{server=\"$server\"}",
     "legendFormat": "{{server}}"
    }
   ]
  }
 ]
}